[package]
name = "docker-engine"
version = "0.1.0"
authors = ["hungryotter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shiplift = "0.6"
